version: "3"

services:
  app:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/psql/5432; do sleep 1; done; alembic upgrade head; uvicorn main:app --port 8000 --host 0.0.0.0 --reload'
    depends_on:
      - psql
    volumes:
      - .:/app/
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}'
    restart: on-failure

  psql:
    image: postgres:14-alpine
    expose:
      - 5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U chain" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    command: nginx -g 'daemon off;'
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/static
    ports:
      - "8000:8000"


volumes:
  psql_data:
  static: